FROM postgres:latest

RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8

COPY fruits.sql /docker-entrypoint-initdb.d
ENV POSTGRES_USER=quarkus
ENV POSTGRES_PASSWORD=quarkus
ENV POSTGRES_DB=quarkus
EXPOSE 5432
